### PR TITLE
Add retry on transient errors logic

### PR DESCRIPTION
**Pull request by kingtong**
From time to time I receive some transient errors from our Netbox instance and / or the proxy that sits between.

This PR adds the retry mechanism for transient errors.

### CODE REVIEW

**Comment by zachmoody** [comment]
:wave:  The [docs](https://pynetbox.readthedocs.io/en/latest/advanced.html#timeouts) already have instructions on timeout handling.

**Comment by zachmoody** [comment]
:wave:  I think you should be able to use the [custom sessions pattern](https://pynetbox.readthedocs.io/en/latest/advanced.html#custom-sessions) to handle retries as well.

**Comment by markkuleinio** [comment]
Example:

```
import pynetbox
import requests
from requests.adapters import HTTPAdapter
from urllib3 import Retry

nb = pynetbox.api(YOUR_NETBOX_URL, YOUR_NETBOX_TOKEN)
retry = Retry(total=5, backoff_factor=1, status_forcelist=[429, 500, 502, 503, 504], allowed_methods=None)
nb.http_session = requests.Session()
nb.http_session.mount("http://", HTTPAdapter(max_retries=retry)) # change to https if used
```

Test with stopping the netbox service on the server so that nginx/apache will return "502 Bad Gateway" errors. See that a simple `nb.version` call will return at 30 seconds with `requests.exceptions.RetryError: HTTPConnectionPool(host='netbox-test.lein.io', port=80): Max retries exceeded with url: /api/ (Caused by ResponseError('too many 502 error responses'))`.

With `total=5` and `backoff_factor=1` the retries will happen at 0, 2, 4, 8 and 16 seconds (total = 30).

Docs: https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#module-urllib3.util.retry

**Comment by kingtong** [comment]
Thanks a lot for the feedback.
Indeed, relying on a custom session with the `Retry` will meet my need.
Closing the PR.

**Pull request closed without merging**
