### PR TITLE
Added a basic precommit configuration

### PR DESCRIPTION
**Pull request by raddessi**
Just because I could, and there are enough differences that I keep on having to install the older version of black locally then revert it to get linting checks to pass.

If you're open to it.. I could set up https://pre-commit.com/ so that this all happens in a venv on the developer's side automatically. It's a great system. Thanks!

### CODE REVIEW

**Comment by raddessi** [comment]
I needed to update this so I thought why not change to a basic precommit setup just to get your thoughts. There are a lot of files change here but all except two were changes via precommit. I created the precommit connfig file ` .pre-commit-config.yaml` and then added precommit to the dev requirements file and then changed the linter command in the github workflow to run precommit instead of black directly. After that, I just ran `pre-commit run --all` to run precommit across the entire codebase.

**Comment by raddessi** [comment]
And later on, if you want, you can have github auto update your linter versions and create PRs for you wutomagically via something like https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/

**Comment by raddessi** [comment]
Hey @zachmoody is this something that you would be interested in or should I revert back to just updating the black version requirement?

**Comment by zachmoody** [comment]
Yeah, do want to get around to doing it. Need to work out all the bugs from the new release first. Also been dragging my feet waiting on vim-black to support venvs. :smile: I think that's maybe be there now though.

**Comment by raddessi** [comment]
Right on, I'm not trying to push it immediately I just wanted to get your opinion before i rebased this with all the 6.x changes. Good to hear, thanks! I'll keep this updated. 6.x looks great so far, hopefully I'll be adding some tests soon.

**Comment by raddessi** [comment]
Closing this for now, maybe I'll reopen in the future :)

**Pull request closed without merging**
