### PR TITLE
Relax upper limit of packaging version

### PR DESCRIPTION
**Pull request by frenzymadness**
It seems to me that pynetbox should work with packaging 24 but I'm not able to run all tests because I don't have docker installed.

### CODE REVIEW

**Comment by frenzymadness** [comment]
It builds fine in Fedora Linux with packaging 24.0

**Comment by markkuleinio** [comment]
If I looked it correctly, `packaging` is only used for `version`. To be honest, I find it to be such a simple use and core function of `packaging` that I don't think it needs any kind of version number pinning.

**Comment by frenzymadness** [comment]
> If I looked it correctly, `packaging` is only used for `version`. To be honest, I find it to be such a simple use and core function of `packaging` that I don't think it needs any kind of version number pinning.

That sounds even better from my point of view. Should I update this PR?

**Comment by markkuleinio** [comment]
I'd say so yes.

**Comment by frenzymadness** [comment]
Done and force-pushed.

**Comment by gaige** [comment]
I'd appreciate seeing this one accepted.

I am not sure if others are encountering this, but the <24.0 requirement is causing some difficulties in aligning with code that I'm using that wants packaging 24.x.

**Pull request merged**
