### PR TITLE
Create GraphQL Interface

### LINKED ISSUE #405: Feature request: GraphQL support
Hello,

is there a planned GraphQL queries implementation since Netbox 3.0 support this feature? 
GraphQL is not part of '/api' endpoint but it has own 'graphql/' path.

Is it possible to implement the GraphQL queries into the pynetbox? 

Thank you

### PR DESCRIPTION
**Pull request by Kani999**
Closes #405

### CODE REVIEW

**Comment by Kani999** [comment]
- Tested against Netbox v3.0.3
- Code copied and edited from `pynautobot`

**Comment by ryanmerolle** [comment]
Hello @Kani999 please resolve conflicts and rebase.  I will try to discuss this with @zachmoody some more.

**Comment by ryanmerolle** [comment]
@zachmoody could you please approve the CI workflow given @Kani999 is a first time contributor to the repo, its a hurdle github puts in place.

**Comment by arthanson** [comment]
IMHO I think this is outside the scope of this project, I'd suggest creating a separate project that is for GraphQL, There is enough issues for this project just for REST API.

**Pull request closed without merging**
